In [1]:
import pandas as pd

In [2]:
y2021 = pd.read_csv("/Users/jianingcai/Downloads/ACSDP1Y2021.DP03-2023-06-21T153034.csv")
df2021 = pd.DataFrame(y2021)
df2021un = df2021.loc[df2021['Alabama!!Estimate'] == "123,808"]
df2021un.insert(1, "year", "2021", True)
df2021un

,Label (Grouping),year,Alabama!!Estimate,Alabama!!Margin of Error,Alabama!!Percent,Alabama!!Percent Margin of Error,Alaska!!Estimate,Alaska!!Margin of Error,Alaska!!Percent,Alaska!!Percent Margin of Error,...,Wisconsin!!Percent,Wisconsin!!Percent Margin of Error,Wyoming!!Estimate,Wyoming!!Margin of Error,Wyoming!!Percent,Wyoming!!Percent Margin of Error,Puerto Rico!!Estimate,Puerto Rico!!Margin of Error,Puerto Rico!!Percent,Puerto Rico!!Percent Margin of Error
5,Unemployed,2021,"123,808","±8,209",3.1%,±0.2,"24,603","±2,254",4.3%,±0.4,...,2.3%,±0.1,"11,171","±2,331",2.4%,±0.5,"163,354","±9,354",5.8%,±0.3

In [3]:
y2020 = pd.read_csv("/Users/jianingcai/Downloads/ACSDP5Y2020.DP03-2023-06-21T153211.csv")
df2020 = pd.DataFrame(y2020)
df2020un = df2020.loc[df2020['Alabama!!Estimate'] == "125,343"]
df2020un.insert(1, "year", "2020", True)
df2020un

,Label (Grouping),year,Alabama!!Estimate,Alabama!!Margin of Error,Alabama!!Percent,Alabama!!Percent Margin of Error,Alaska!!Estimate,Alaska!!Margin of Error,Alaska!!Percent,Alaska!!Percent Margin of Error,...,Wisconsin!!Percent,Wisconsin!!Percent Margin of Error,Wyoming!!Estimate,Wyoming!!Margin of Error,Wyoming!!Percent,Wyoming!!Percent Margin of Error,Puerto Rico!!Estimate,Puerto Rico!!Margin of Error,Puerto Rico!!Percent,Puerto Rico!!Percent Margin of Error
5,Unemployed,2020,"125,343","±3,022",3.2%,±0.1,"26,429","±1,151",4.6%,±0.2,...,2.3%,±0.1,"13,222",±959,2.9%,±0.2,"182,171","±3,523",6.7%,±0.1

In [4]:
y2019 = pd.read_csv("/Users/jianingcai/Downloads/ACSDP1Y2019.DP03-2023-06-21T153231.csv")
df2019 = pd.DataFrame(y2019)
df2019un = df2019.loc[df2019['Alabama!!Estimate'] == "111,622"]
df2019un.insert(1, "year", "2019", True)
df2019un

,Label (Grouping),year,Alabama!!Estimate,Alabama!!Margin of Error,Alabama!!Percent,Alabama!!Percent Margin of Error,Alaska!!Estimate,Alaska!!Margin of Error,Alaska!!Percent,Alaska!!Percent Margin of Error,...,Wisconsin!!Percent,Wisconsin!!Percent Margin of Error,Wyoming!!Estimate,Wyoming!!Margin of Error,Wyoming!!Percent,Wyoming!!Percent Margin of Error,Puerto Rico!!Estimate,Puerto Rico!!Margin of Error,Puerto Rico!!Percent,Puerto Rico!!Percent Margin of Error
5,Unemployed,2019,"111,622","±7,022",2.8%,±0.2,"20,650","±2,390",3.6%,±0.4,...,2.1%,±0.1,"10,539","±1,720",2.3%,±0.4,"171,370","±8,258",6.3%,±0.3

In [5]:
y2018 = pd.read_csv("/Users/jianingcai/Downloads/ACSDP1Y2018.DP03-2023-06-21T153240.csv")
df2018 = pd.DataFrame(y2018)
df2018un = df2018.loc[df2018['Alabama!!Estimate'] == "124,835"]
df2018un.insert(1, "year", "2018", True)
df2018un

,Label (Grouping),year,Alabama!!Estimate,Alabama!!Margin of Error,Alabama!!Percent,Alabama!!Percent Margin of Error,Alaska!!Estimate,Alaska!!Margin of Error,Alaska!!Percent,Alaska!!Percent Margin of Error,...,Wisconsin!!Percent,Wisconsin!!Percent Margin of Error,Wyoming!!Estimate,Wyoming!!Margin of Error,Wyoming!!Percent,Wyoming!!Percent Margin of Error,Puerto Rico!!Estimate,Puerto Rico!!Margin of Error,Puerto Rico!!Percent,Puerto Rico!!Percent Margin of Error
5,Unemployed,2018,"124,835","±7,615",3.2%,±0.2,"25,410","±1,930",4.4%,±0.3,...,2.1%,±0.1,"11,684","±1,906",2.5%,±0.4,"178,219","±8,193",6.6%,±0.3

In [6]:
y2017 = pd.read_csv("/Users/jianingcai/Downloads/ACSDP1Y2017.DP03-2023-06-21T153249.csv")
df2017 = pd.DataFrame(y2017)
df2017un = df2017.loc[df2017['Alabama!!Estimate'] == "128,302"]
df2017un.insert(1, "year", "2017", True)
df2017un

,Label (Grouping),year,Alabama!!Estimate,Alabama!!Margin of Error,Alabama!!Percent,Alabama!!Percent Margin of Error,Alaska!!Estimate,Alaska!!Margin of Error,Alaska!!Percent,Alaska!!Percent Margin of Error,...,Wisconsin!!Percent,Wisconsin!!Percent Margin of Error,Wyoming!!Estimate,Wyoming!!Margin of Error,Wyoming!!Percent,Wyoming!!Percent Margin of Error,Puerto Rico!!Estimate,Puerto Rico!!Margin of Error,Puerto Rico!!Percent,Puerto Rico!!Percent Margin of Error
5,Unemployed,2017,"128,302","±6,480",3.3%,±0.2,"28,267","±2,745",4.9%,±0.5,...,2.3%,±0.1,"15,376","±2,432",3.4%,±0.5,"196,859","±8,771",7.1%,±0.3

In [7]:
y2016 = pd.read_csv("/Users/jianingcai/Downloads/ACSDP1Y2016.DP03-2023-06-21T154605.csv")
df2016 = pd.DataFrame(y2016)
df2016un = df2016.loc[df2016['Alabama!!Estimate'] == "140,963"]
df2016un.insert(1, "year", "2016", True)
df2016un

,Label (Grouping),year,Alabama!!Estimate,Alabama!!Margin of Error,Alabama!!Percent,Alabama!!Percent Margin of Error,Alaska!!Estimate,Alaska!!Margin of Error,Alaska!!Percent,Alaska!!Percent Margin of Error,...,Wisconsin!!Percent,Wisconsin!!Percent Margin of Error,Wyoming!!Estimate,Wyoming!!Margin of Error,Wyoming!!Percent,Wyoming!!Percent Margin of Error,Puerto Rico!!Estimate,Puerto Rico!!Margin of Error,Puerto Rico!!Percent,Puerto Rico!!Percent Margin of Error
5,Unemployed,2016,"140,963","±6,314",3.6%,±0.2,"30,964","±3,145",5.4%,±0.5,...,2.7%,±0.1,"17,000","±1,977",3.7%,±0.4,"202,760","±8,681",7.2%,±0.3

In [8]:
y2015 = pd.read_csv("/Users/jianingcai/Downloads/ACSDP1Y2015.DP03-2023-06-21T154612.csv")
df2015 = pd.DataFrame(y2015)
df2015un = df2015.loc[df2015['Alabama!!Estimate'] == "157,544"]
df2015un.insert(1, "year", "2015", True)
df2015un

,Label (Grouping),year,Alabama!!Estimate,Alabama!!Margin of Error,Alabama!!Percent,Alabama!!Percent Margin of Error,Alaska!!Estimate,Alaska!!Margin of Error,Alaska!!Percent,Alaska!!Percent Margin of Error,...,Wisconsin!!Percent,Wisconsin!!Percent Margin of Error,Wyoming!!Estimate,Wyoming!!Margin of Error,Wyoming!!Percent,Wyoming!!Percent Margin of Error,Puerto Rico!!Estimate,Puerto Rico!!Margin of Error,Puerto Rico!!Percent,Puerto Rico!!Percent Margin of Error
5,Unemployed,2015,"157,544","±6,651",4.1%,±0.2,"30,399","±2,820",5.3%,±0.5,...,2.8%,±0.1,"15,041","±2,490",3.3%,±0.5,"238,625","±8,401",8.4%,±0.3

In [9]:
y2014 = pd.read_csv("/Users/jianingcai/Downloads/ACSDP1Y2014.DP03-2023-06-21T154619.csv")
df2014 = pd.DataFrame(y2014)
df2014un = df2014.loc[df2014['Alabama!!Estimate'] == "190,233"]
df2014un.insert(1, "year", "2014", True)
df2014un

,Label (Grouping),year,Alabama!!Estimate,Alabama!!Margin of Error,Alabama!!Percent,Alabama!!Percent Margin of Error,Alaska!!Estimate,Alaska!!Margin of Error,Alaska!!Percent,Alaska!!Percent Margin of Error,...,Wisconsin!!Percent,Wisconsin!!Percent Margin of Error,Wyoming!!Estimate,Wyoming!!Margin of Error,Wyoming!!Percent,Wyoming!!Percent Margin of Error,Puerto Rico!!Estimate,Puerto Rico!!Margin of Error,Puerto Rico!!Percent,Puerto Rico!!Percent Margin of Error
5,Unemployed,2014,"190,233","±7,184",4.9%,±0.2,"29,164","±2,352",5.1%,±0.4,...,3.5%,±0.1,"13,477","±2,065",2.9%,±0.4,"237,292","±8,997",8.2%,±0.3

In [10]:
y2013 = pd.read_csv("/Users/jianingcai/Downloads/ACSDP1Y2013.DP03-2023-06-21T154630.csv")
df2013 = pd.DataFrame(y2013)
df2013un = df2013.loc[df2013['Alabama!!Estimate'] == "214,268"]
df2013un.insert(1, "year", "2013", True)
df2013un

,Label (Grouping),year,Alabama!!Estimate,Alabama!!Margin of Error,Alabama!!Percent,Alabama!!Percent Margin of Error,Alaska!!Estimate,Alaska!!Margin of Error,Alaska!!Percent,Alaska!!Percent Margin of Error,...,Wisconsin!!Percent,Wisconsin!!Percent Margin of Error,Wyoming!!Estimate,Wyoming!!Margin of Error,Wyoming!!Percent,Wyoming!!Percent Margin of Error,Puerto Rico!!Estimate,Puerto Rico!!Margin of Error,Puerto Rico!!Percent,Puerto Rico!!Percent Margin of Error
5,Unemployed,2013,"214,268","±8,755",5.6%,±0.2,"33,687","±2,918",6.0%,±0.5,...,4.3%,±0.1,"15,775","±1,968",3.4%,±0.4,"235,338","±8,388",8.1%,±0.3

In [11]:
y2012 = pd.read_csv("/Users/jianingcai/Downloads/ACSDP1Y2012.DP03-2023-06-21T154637.csv")
df2012 = pd.DataFrame(y2012)
df2012un = df2012.loc[df2012['Alabama!!Estimate'] == "222,017"]
df2012un.insert(1, "year", "2012", True)
df2012un

,Label (Grouping),year,Alabama!!Estimate,Alabama!!Margin of Error,Alabama!!Percent,Alabama!!Percent Margin of Error,Alaska!!Estimate,Alaska!!Margin of Error,Alaska!!Percent,Alaska!!Percent Margin of Error,...,Wisconsin!!Percent,Wisconsin!!Percent Margin of Error,Wyoming!!Estimate,Wyoming!!Margin of Error,Wyoming!!Percent,Wyoming!!Percent Margin of Error,Puerto Rico!!Estimate,Puerto Rico!!Margin of Error,Puerto Rico!!Percent,Puerto Rico!!Percent Margin of Error
5,Unemployed,2012,"222,017","±8,226",5.8%,±0.2,"29,864","±2,563",5.3%,±0.5,...,4.9%,±0.2,"17,113","±2,195",3.8%,±0.5,"229,733","±8,796",7.9%,±0.3

In [12]:
y2011 = pd.read_csv("/Users/jianingcai/Downloads/ACSDP1Y2011.DP03-2023-06-21T154644.csv")
df2011 = pd.DataFrame(y2011)
df2011un = df2011.loc[df2011['Alabama!!Estimate'] == "259,346"]
df2011un.insert(1, "year", "2011", True)
df2011un

,Label (Grouping),year,Alabama!!Estimate,Alabama!!Margin of Error,Alabama!!Percent,Alabama!!Percent Margin of Error,Alaska!!Estimate,Alaska!!Margin of Error,Alaska!!Percent,Alaska!!Percent Margin of Error,...,Wisconsin!!Percent,Wisconsin!!Percent Margin of Error,Wyoming!!Estimate,Wyoming!!Margin of Error,Wyoming!!Percent,Wyoming!!Percent Margin of Error,Puerto Rico!!Estimate,Puerto Rico!!Margin of Error,Puerto Rico!!Percent,Puerto Rico!!Percent Margin of Error
5,Unemployed,2011,"259,346","±10,052",6.8%,±0.3,"33,367","±2,880",6.0%,±0.5,...,5.5%,±0.2,"15,553","±2,116",3.5%,±0.5,"250,105","±7,757",8.5%,±0.3

In [13]:
y2010 = pd.read_csv("/Users/jianingcai/Downloads/ACSDP1Y2010.DP03-2023-06-21T154651.csv")
df2010 = pd.DataFrame(y2010)
df2010un = df2010.loc[df2010['Alabama!!Estimate'] == "265,383"]
df2010un.insert(1, "year", "2010", True)
df2010un

,Label (Grouping),year,Alabama!!Estimate,Alabama!!Estimate Margin of Error,Alabama!!Percent,Alabama!!Percent Margin of Error,Alaska!!Estimate,Alaska!!Estimate Margin of Error,Alaska!!Percent,Alaska!!Percent Margin of Error,...,Wisconsin!!Percent,Wisconsin!!Percent Margin of Error,Wyoming!!Estimate,Wyoming!!Estimate Margin of Error,Wyoming!!Percent,Wyoming!!Percent Margin of Error,Puerto Rico!!Estimate,Puerto Rico!!Estimate Margin of Error,Puerto Rico!!Percent,Puerto Rico!!Percent Margin of Error
5,Unemployed,2010,"265,383","±9,010",7.0%,±0.2,"36,020","±2,726",6.6%,±0.5,...,6.1%,±0.2,"18,779","±2,236",4.2%,±0.5,"262,808","±8,186",8.9%,±0.3

In [14]:
dftotal = df2021un.join(df2020un.set_index(list(df2021un)), on=list(df2021un.columns), how="outer")
dftotal = dftotal.join(df2019un.set_index(list(dftotal.columns)), on=list(dftotal.columns), how="outer")
dftotal = dftotal.join(df2018un.set_index(list(dftotal.columns)), on=list(dftotal.columns), how="outer")
dftotal = dftotal.join(df2017un.set_index(list(dftotal.columns)), on=list(dftotal.columns), how="outer")
dftotal = dftotal.join(df2016un.set_index(list(dftotal.columns)), on=list(dftotal.columns), how="outer")
dftotal = dftotal.join(df2015un.set_index(list(dftotal.columns)), on=list(dftotal.columns), how="outer")
dftotal = dftotal.join(df2014un.set_index(list(dftotal.columns)), on=list(dftotal.columns), how="outer")
dftotal = dftotal.join(df2013un.set_index(list(dftotal.columns)), on=list(dftotal.columns), how="outer")
dftotal = dftotal.join(df2012un.set_index(list(dftotal.columns)), on=list(dftotal.columns), how="outer")
dftotal = dftotal.join(df2011un.set_index(list(dftotal.columns)), on=list(dftotal.columns), how="outer")
dftotal = dftotal.join(df2010un.set_index(list(df2010un.columns)), on=list(dftotal.columns), how="outer")
dftotal

,Label (Grouping),year,Alabama!!Estimate,Alabama!!Margin of Error,Alabama!!Percent,Alabama!!Percent Margin of Error,Alaska!!Estimate,Alaska!!Margin of Error,Alaska!!Percent,Alaska!!Percent Margin of Error,...,Wisconsin!!Percent,Wisconsin!!Percent Margin of Error,Wyoming!!Estimate,Wyoming!!Margin of Error,Wyoming!!Percent,Wyoming!!Percent Margin of Error,Puerto Rico!!Estimate,Puerto Rico!!Margin of Error,Puerto Rico!!Percent,Puerto Rico!!Percent Margin of Error
5,Unemployed,2021,"123,808","±8,209",3.1%,±0.2,"24,603","±2,254",4.3%,±0.4,...,2.3%,±0.1,"11,171","±2,331",2.4%,±0.5,"163,354","±9,354",5.8%,±0.3
5,Unemployed,2020,"125,343","±3,022",3.2%,±0.1,"26,429","±1,151",4.6%,±0.2,...,2.3%,±0.1,"13,222",±959,2.9%,±0.2,"182,171","±3,523",6.7%,±0.1
5,Unemployed,2019,"111,622","±7,022",2.8%,±0.2,"20,650","±2,390",3.6%,±0.4,...,2.1%,±0.1,"10,539","±1,720",2.3%,±0.4,"171,370","±8,258",6.3%,±0.3
5,Unemployed,2018,"124,835","±7,615",3.2%,±0.2,"25,410","±1,930",4.4%,±0.3,...,2.1%,±0.1,"11,684","±1,906",2.5%,±0.4,"178,219","±8,193",6.6%,±0.3
5,Unemployed,2017,"128,302","±6,480",3.3%,±0.2,"28,267","±2,745",4.9%,±0.5,...,2.3%,±0.1,"15,376","±2,432",3.4%,±0.5,"196,859","±8,771",7.1%,±0.3
5,Unemployed,2016,"140,963","±6,314",3.6%,±0.2,"30,964","±3,145",5.4%,±0.5,...,2.7%,±0.1,"17,000","±1,977",3.7%,±0.4,"202,760","±8,681",7.2%,±0.3
5,Unemployed,2015,"157,544","±6,651",4.1%,±0.2,"30,399","±2,820",5.3%,±0.5,...,2.8%,±0.1,"15,041","±2,490",3.3%,±0.5,"238,625","±8,401",8.4%,±0.3
5,Unemployed,2014,"190,233","±7,184",4.9%,±0.2,"29,164","±2,352",5.1%,±0.4,...,3.5%,±0.1,"13,477","±2,065",2.9%,±0.4,"237,292","±8,997",8.2%,±0.3
5,Unemployed,2013,"214,268","±8,755",5.6%,±0.2,"33,687","±2,918",6.0%,±0.5,...,4.3%,±0.1,"15,775","±1,968",3.4%,±0.4,"235,338","±8,388",8.1%,±0.3
5,Unemployed,2012,"222,017","±8,226",5.8%,±0.2,"29,864","±2,563",5.3%,±0.5,...,4.9%,±0.2,"17,113","±2,195",3.8%,±0.5,"229,733","±8,796",7.9%,±0.3
5,Unemployed,2011,"259,346","±10,052",6.8%,±0.3,"33,367","±2,880",6.0%,±0.5,...,5.5%,±0.2,"15,553","±2,116",3.5%,±0.5,"250,105","±7,757",8.5%,±0.3
5,Unemployed,2010,"265,383","±9,010",7.0%,±0.2,"36,020","±2,726",6.6%,±0.5,...,6.1%,±0.2,"18,779","±2,236",4.2%,±0.5,"262,808","±8,186",8.9%,±0.3

In [15]:
dftotal.to_csv("/Users/jianingcai/Downloads/unemp_state_year.csv")